# server
server:
  port: 443 # SSL
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: potenday312!

# jasypt (μ•”νΈν™”)
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: potenday312!

spring:
#  profiles:
#    location: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(0U8kjxbUALGpt7iJ3ESX6w==)
    password: ENC(6kfPXxVaR3M4VgfEnzv/Rg==)
    url: ENC(MntShJb3r7KeTw3g6LDufbpMt6x3R+CwuUMV3QIw0Ewd4MPkBo1MVS1c06tvfBKJjRwp2TcBGHiPjpfqjjZninPIPyoaCifL3OWOsMGxXXI=)

# Mybatis
mybatis:
  type-aliases-package: com.be.poten.domain
  mapper-locations: mapper/*.xml